---
title: "DATA607 - Recommender Systems"
author: "Lucas Weyrich"
date: "2024-04-05"
output: html_document
---
I do not have the app TikTok installed on my phone. If you to my app store, you will not see a cloud (indicator that it was downloaded before), but you will see the word 'get'. Nevertheless, I have not been immune to the fascination for TikTok's famous algorithm that is apparently so strong it pushes people's screen time into spaces that would have been considered an addiction just a few years ago.

What makes this algorithm so strong? So effiicent, and so 'addicting'? Most people know that there is some type of algorithm behind TikTok, as well as many other social media and shopping technologies (often intertwined these days). But most people don't know what exact algorithm is behind this: it is a recommender system, learning from user-behavior to predict something (i.e., a product, a video) that a user will like. 

In the case of TikTok, I have come across a NYT article (reference on the bottom) that discusses a document, which was circulated among TikTok employees called 'TikTok Alg 101'. The document even presented a rough schema of the recommender system, namely being: Plike X Vlike + Pcomment X Vcomment + Eplaytime X Vplaytime + Pplay X Vplay. While the actualy system used is more complex, the logic can be inferred. What strikes is that, with videos of one minute or less, the play time matters. This means that if a user is watching video A for 3 seconds, but video B for 30 seconds, and in video A a country-genre song played, but in video B it was a hip-hop genre song, it can be inferred that the user may enjoy listening to hip-hop more. The strength comes with two factors. Firstly, one swipe up will show the next video. One finger stroke. The availability is instant. Secondly, since the videos are kept so short from the beginning, the recommender system can create exact tailored recommendations very efficiently and fast. Compared to other recommender systems, such as Netflix or Amazon, where a user has to watch at least a few hours, or shop for a few products, which is also more on the hourly scale, TikTok's recommender has many data points within the first ten minutes of usage.

While there are many concerns in the United States about the fact that TikTok is from China, and hence all these data points are saved there with different privacy laws than in the US, the more important factor is that this type of recommender system can create sever bubbles. Not just the classic political bubbles like left versus right, but bubbles that cater to all kinds of human personality traits, and often reinforce them: depression, anger issues, even paedophilia given the lack of age restrictions for the app. Therefore, the recommender system of TikTok does not necessarily have a target population. Any human will be sucked into watching very short videos that are so tailored it's almost impossible to look away. This makes TikTok one of the most influential recommender systems there currently is, and many other social media companies and other industries have followed suit.

My recommendations for this recommender system, to improve it, is quite unintuitive: bring in more variety. At random, introduce a video that may even be the opposite of what the algorithm would have shown, and have a separate recommender system record these responses. Several benefits come to light here. Societal, many bubbles can be mitigated and the mental health of every user, but especially of vulnerable adolescents (although, as has shown, the population over 40 is by any means not much more immune), will not be as deteriorated as it currently is the case. This deterioration has a simple psychological explanation: humans enjoy to watch what they don't have, but what they would like. However, continuous exposure can lead to depression. Commercially, intorducing randomness into the system may increase the chances of creating novelty. There are, of course, no actual statistics avaialble on the drop-out rate, and after how long of usage. Although it seems reasonable to believe that the same types of videos will inevitably create boredom. Since the primary goal is to keep the user engaged as long as possible, randomness may uncover new interests that the user enjoys and keeps the user engaged longer.

https://www.nytimes.com/2021/12/05/business/media/tiktok-algorithm.html